# Generated by Django 4.2.30 on 2026-09-08 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import students.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WrestlingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('notes_to_coach', models.TextField(blank=True, default='', verbose_name='notes to coach')),
                ('video_file', models.FileField(upload_to=students.models.student_video_upload_to, verbose_name='video file')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('PENDING_REVIEW', 'Pending coach review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed')], db_index=True, default='UPLOADED', max_length=20)),
                ('coach_review_status', models.CharField(choices=[('NOT_REQUIRED', 'Not required'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='NOT_REQUIRED', max_length=20)),
                ('coach_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('coach_review_comment', models.TextField(blank=True, default='')),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(blank=True, db_column='coach_id', limit_choices_to={'role': 'COACH'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coached_videos', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(db_column='student_id', limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'wrestling video',
                'verbose_name_plural': 'wrestling videos',
                'db_table': 'students_wrestlingvideo',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', '-created_at'], name='students_wr_student_bfc17c_idx'), models.Index(fields=['coach', 'coach_review_status'], name='students_wr_coach_i_f947d9_idx'), models.Index(fields=['status'], name='students_wr_status_1c53f3_idx')],
            },
        ),
    ]
