# Generated by Django 4.2.30 on 2026-09-08 12:22

from django.db import migrations, models
import django.db.models.deletion
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_wrestling_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, default='')),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.OneToOneField(db_column='video_id', on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='students.wrestlingvideo')),
            ],
            options={
                'verbose_name': 'video analysis',
                'verbose_name_plural': 'video analyses',
                'db_table': 'students_videoanalysis',
            },
        ),
        migrations.CreateModel(
            name='AnalysisMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_name', models.CharField(max_length=200)),
                ('timestamp_seconds', models.FloatField(default=0)),
                ('ai_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_suggestion', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('frame_image', models.ImageField(blank=True, null=True, upload_to=students.models.analysis_frame_upload_to)),
                ('analysis', models.ForeignKey(db_column='analysis_id', on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='students.videoanalysis')),
            ],
            options={
                'verbose_name': 'analysis movement',
                'verbose_name_plural': 'analysis movements',
                'db_table': 'students_analysismovement',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
