# Generated by Django 4.2.30 on 2026-09-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_video_analysis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysismovement',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'analysis frame', 'verbose_name_plural': 'analysis frames'},
        ),
        migrations.AddField(
            model_name='analysismovement',
            name='coach_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='analysismovement',
            name='coach_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysismovement',
            name='phase',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='analysismovement',
            name='technical_evaluation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='analysismovement',
            name='visual_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='analysismovement',
            name='movement_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
