# Generated by Django 4.2.30 on 2026-09-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_copy_phase_from_movement_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoanalysis',
            name='match_analysis',
            field=models.JSONField(blank=True, default=dict, help_text='Top-level match summary (event, wrestlers, winner, finish, summary).'),
        ),
    ]
